/*
 * PiggiesMerchantService
 * Valida o merchant e registra o crédito. Merchant ACTIVE segue no fluxo. INACTIVE ou CNPJ desconhecido interrompem o pagamento.  Entidades persistidas no schema spp_merchant: Merchant e Receivable.  paymentIntentId é único no recebível. Repetir o crédito devolve o mesmo Receivable sem criar outra linha.  Consome spp.payment.confirm e publica spp.payment.confirmed depois do crédito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.merchant.api.model;

import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.annotation.Generated;

/**
 * Gets or Sets ReceivableStatus
 */
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public enum ReceivableStatus {

    @JsonProperty("CREDITED")
    CREDITED("CREDITED"),
    ;

    public static final Map<String, ReceivableStatus> VALUE_MAPPING = Map.copyOf(Arrays.stream(values())

        .collect(Collectors.toMap(v -> v.value, Function.identity())));

    private final String value;

    ReceivableStatus(String value) {
        this.value = value;
    }

    /**
     * @return The value represented by this enum
     */
    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    /**
     * Create this enum from a value.
     *
     * @param value The value
     *
     * @return The enum
     */
    @JsonCreator
    public static ReceivableStatus fromValue(String value) {
        if (!VALUE_MAPPING.containsKey(value)) {
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
        return VALUE_MAPPING.get(value);
    }
}