/*
 * PiggiesMerchantService
 * Valida o merchant e registra o crédito. Merchant ACTIVE segue no fluxo. INACTIVE ou CNPJ desconhecido interrompem o pagamento.  Entidades persistidas no schema spp_merchant: Merchant e Receivable.  paymentIntentId é único no recebível. Repetir o crédito devolve o mesmo Receivable sem criar outra linha.  Consome spp.payment.confirm e publica spp.payment.confirmed depois do crédito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.merchant.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import co.inter.piggies.merchant.api.model.ReceivableStatus;
import java.time.ZonedDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Receivable
 */
@JsonPropertyOrder({
    Receivable.JSON_PROPERTY_ID,
    Receivable.JSON_PROPERTY_PAYMENT_INTENT_ID,
    Receivable.JSON_PROPERTY_MERCHANT_ID,
    Receivable.JSON_PROPERTY_AMOUNT,
    Receivable.JSON_PROPERTY_STATUS,
    Receivable.JSON_PROPERTY_CREDITED_AT,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class Receivable {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_PAYMENT_INTENT_ID = "paymentIntentId";
    public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
    public static final String JSON_PROPERTY_AMOUNT = "amount";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_CREDITED_AT = "creditedAt";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private UUID id;

    /**
     * Único. Impede crédito duplo do mesmo pagamento.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
    private UUID paymentIntentId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
    private UUID merchantId;

    @NotNull
    @Min(1L)
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    private Long amount;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private ReceivableStatus status;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CREDITED_AT)
    private ZonedDateTime creditedAt;

    public Receivable(UUID id, UUID paymentIntentId, UUID merchantId, Long amount, ReceivableStatus status, ZonedDateTime creditedAt) {
        this.id = id;
        this.paymentIntentId = paymentIntentId;
        this.merchantId = merchantId;
        this.amount = amount;
        this.status = status;
        this.creditedAt = creditedAt;
    }

    /**
     * @return the id property value
     */
    public UUID getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of Receivable for chaining.
     */
    public Receivable id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Único. Impede crédito duplo do mesmo pagamento.
     *
     * @return the paymentIntentId property value
     */
    public UUID getPaymentIntentId() {
        return paymentIntentId;
    }

    /**
     * Set the paymentIntentId property value
     *
     * @param paymentIntentId property value to set
     */
    public void setPaymentIntentId(UUID paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
    }

    /**
     * Set paymentIntentId in a chainable fashion.
     *
     * @return The same instance of Receivable for chaining.
     */
    public Receivable paymentIntentId(UUID paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
        return this;
    }

    /**
     * @return the merchantId property value
     */
    public UUID getMerchantId() {
        return merchantId;
    }

    /**
     * Set the merchantId property value
     *
     * @param merchantId property value to set
     */
    public void setMerchantId(UUID merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * Set merchantId in a chainable fashion.
     *
     * @return The same instance of Receivable for chaining.
     */
    public Receivable merchantId(UUID merchantId) {
        this.merchantId = merchantId;
        return this;
    }

    /**
     * @return the amount property value
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Set the amount property value
     *
     * @param amount property value to set
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * Set amount in a chainable fashion.
     *
     * @return The same instance of Receivable for chaining.
     */
    public Receivable amount(Long amount) {
        this.amount = amount;
        return this;
    }

    /**
     * @return the status property value
     */
    public ReceivableStatus getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(ReceivableStatus status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of Receivable for chaining.
     */
    public Receivable status(ReceivableStatus status) {
        this.status = status;
        return this;
    }

    /**
     * @return the creditedAt property value
     */
    public ZonedDateTime getCreditedAt() {
        return creditedAt;
    }

    /**
     * Set the creditedAt property value
     *
     * @param creditedAt property value to set
     */
    public void setCreditedAt(ZonedDateTime creditedAt) {
        this.creditedAt = creditedAt;
    }

    /**
     * Set creditedAt in a chainable fashion.
     *
     * @return The same instance of Receivable for chaining.
     */
    public Receivable creditedAt(ZonedDateTime creditedAt) {
        this.creditedAt = creditedAt;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var receivable = (Receivable) o;
        return Objects.equals(this.id, receivable.id)
            && Objects.equals(this.paymentIntentId, receivable.paymentIntentId)
            && Objects.equals(this.merchantId, receivable.merchantId)
            && Objects.equals(this.amount, receivable.amount)
            && Objects.equals(this.status, receivable.status)
            && Objects.equals(this.creditedAt, receivable.creditedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, paymentIntentId, merchantId, amount, status, creditedAt);
    }

    @Override
    public String toString() {
        return "Receivable("
            + "id: " + getId() + ", "
            + "paymentIntentId: " + getPaymentIntentId() + ", "
            + "merchantId: " + getMerchantId() + ", "
            + "amount: " + getAmount() + ", "
            + "status: " + getStatus() + ", "
            + "creditedAt: " + getCreditedAt()
            + ")";
    }

}