/*
 * PiggiesMerchantService
 * Valida o merchant e registra o crédito. Merchant ACTIVE segue no fluxo. INACTIVE ou CNPJ desconhecido interrompem o pagamento.  Entidades persistidas no schema spp_merchant: Merchant e Receivable.  paymentIntentId é único no recebível. Repetir o crédito devolve o mesmo Receivable sem criar outra linha.  Consome spp.payment.confirm e publica spp.payment.confirmed depois do crédito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.merchant.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * ValidateMerchantRequest
 */
@JsonPropertyOrder(ValidateMerchantRequest.JSON_PROPERTY_MERCHANT_CNPJ)
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ValidateMerchantRequest {

    public static final String JSON_PROPERTY_MERCHANT_CNPJ = "merchantCnpj";

    /**
     * CNPJ do Merchant, só dígitos.
     */
    @NotNull
    @Pattern(regexp = "^[0-9]{14}$")
    @JsonProperty(JSON_PROPERTY_MERCHANT_CNPJ)
    private String merchantCnpj;

    public ValidateMerchantRequest(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
    }

    /**
     * CNPJ do Merchant, só dígitos.
     *
     * @return the merchantCnpj property value
     */
    public String getMerchantCnpj() {
        return merchantCnpj;
    }

    /**
     * Set the merchantCnpj property value
     *
     * @param merchantCnpj property value to set
     */
    public void setMerchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
    }

    /**
     * Set merchantCnpj in a chainable fashion.
     *
     * @return The same instance of ValidateMerchantRequest for chaining.
     */
    public ValidateMerchantRequest merchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var validateMerchantRequest = (ValidateMerchantRequest) o;
        return Objects.equals(this.merchantCnpj, validateMerchantRequest.merchantCnpj);
    }

    @Override
    public int hashCode() {
        return Objects.hash(merchantCnpj);
    }

    @Override
    public String toString() {
        return "ValidateMerchantRequest("
            + "merchantCnpj: " + getMerchantCnpj()
            + ")";
    }

}