/*
 * PiggiesReserveService
 * Reserva o saldo do cliente e confirma o débito. Disponível = balance − reservedBalance.  Entidades persistidas no schema spp_reserve: Client, Account e Reservation. Client e Account não têm endpoint próprio nesta versão; a reserva localiza a conta por CPF, agência e número.  paymentIntentId é único. Repetir a criação, a confirmação ou a liberação com o mesmo pagamento não move saldo de novo.  Liberar uma reserva CONFIRMED responde 409. Não há estorno depois do débito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.reserve.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Conta do cliente. Disponível = balance − reservedBalance. Sem endpoint nesta versão; a reserva devolve accountId.
 */
@JsonPropertyOrder({
    Account.JSON_PROPERTY_ID,
    Account.JSON_PROPERTY_CLIENT_ID,
    Account.JSON_PROPERTY_AGENCY,
    Account.JSON_PROPERTY_NUMBER,
    Account.JSON_PROPERTY_BALANCE,
    Account.JSON_PROPERTY_RESERVED_BALANCE,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class Account {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_CLIENT_ID = "clientId";
    public static final String JSON_PROPERTY_AGENCY = "agency";
    public static final String JSON_PROPERTY_NUMBER = "number";
    public static final String JSON_PROPERTY_BALANCE = "balance";
    public static final String JSON_PROPERTY_RESERVED_BALANCE = "reservedBalance";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private UUID id;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CLIENT_ID)
    private UUID clientId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_AGENCY)
    private String agency;

    /**
     * Número da conta.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_NUMBER)
    private String number;

    /**
     * Saldo liquidado, em Piggies.
     */
    @NotNull
    @Min(0L)
    @JsonProperty(JSON_PROPERTY_BALANCE)
    private Long balance;

    /**
     * Soma das reservas ainda em RESERVED.
     */
    @NotNull
    @Min(0L)
    @JsonProperty(JSON_PROPERTY_RESERVED_BALANCE)
    private Long reservedBalance;

    public Account(UUID id, UUID clientId, String agency, String number, Long balance, Long reservedBalance) {
        this.id = id;
        this.clientId = clientId;
        this.agency = agency;
        this.number = number;
        this.balance = balance;
        this.reservedBalance = reservedBalance;
    }

    /**
     * @return the id property value
     */
    public UUID getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of Account for chaining.
     */
    public Account id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * @return the clientId property value
     */
    public UUID getClientId() {
        return clientId;
    }

    /**
     * Set the clientId property value
     *
     * @param clientId property value to set
     */
    public void setClientId(UUID clientId) {
        this.clientId = clientId;
    }

    /**
     * Set clientId in a chainable fashion.
     *
     * @return The same instance of Account for chaining.
     */
    public Account clientId(UUID clientId) {
        this.clientId = clientId;
        return this;
    }

    /**
     * @return the agency property value
     */
    public String getAgency() {
        return agency;
    }

    /**
     * Set the agency property value
     *
     * @param agency property value to set
     */
    public void setAgency(String agency) {
        this.agency = agency;
    }

    /**
     * Set agency in a chainable fashion.
     *
     * @return The same instance of Account for chaining.
     */
    public Account agency(String agency) {
        this.agency = agency;
        return this;
    }

    /**
     * Número da conta.
     *
     * @return the number property value
     */
    public String getNumber() {
        return number;
    }

    /**
     * Set the number property value
     *
     * @param number property value to set
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * Set number in a chainable fashion.
     *
     * @return The same instance of Account for chaining.
     */
    public Account number(String number) {
        this.number = number;
        return this;
    }

    /**
     * Saldo liquidado, em Piggies.
     *
     * @return the balance property value
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * Set the balance property value
     *
     * @param balance property value to set
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * Set balance in a chainable fashion.
     *
     * @return The same instance of Account for chaining.
     */
    public Account balance(Long balance) {
        this.balance = balance;
        return this;
    }

    /**
     * Soma das reservas ainda em RESERVED.
     *
     * @return the reservedBalance property value
     */
    public Long getReservedBalance() {
        return reservedBalance;
    }

    /**
     * Set the reservedBalance property value
     *
     * @param reservedBalance property value to set
     */
    public void setReservedBalance(Long reservedBalance) {
        this.reservedBalance = reservedBalance;
    }

    /**
     * Set reservedBalance in a chainable fashion.
     *
     * @return The same instance of Account for chaining.
     */
    public Account reservedBalance(Long reservedBalance) {
        this.reservedBalance = reservedBalance;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var account = (Account) o;
        return Objects.equals(this.id, account.id)
            && Objects.equals(this.clientId, account.clientId)
            && Objects.equals(this.agency, account.agency)
            && Objects.equals(this.number, account.number)
            && Objects.equals(this.balance, account.balance)
            && Objects.equals(this.reservedBalance, account.reservedBalance);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, clientId, agency, number, balance, reservedBalance);
    }

    @Override
    public String toString() {
        return "Account("
            + "id: " + getId() + ", "
            + "clientId: " + getClientId() + ", "
            + "agency: " + getAgency() + ", "
            + "number: " + getNumber() + ", "
            + "balance: " + getBalance() + ", "
            + "reservedBalance: " + getReservedBalance()
            + ")";
    }

}