/*
 * PiggiesReserveService
 * Reserva o saldo do cliente e confirma o débito. Disponível = balance − reservedBalance.  Entidades persistidas no schema spp_reserve: Client, Account e Reservation. Client e Account não têm endpoint próprio nesta versão; a reserva localiza a conta por CPF, agência e número.  paymentIntentId é único. Repetir a criação, a confirmação ou a liberação com o mesmo pagamento não move saldo de novo.  Liberar uma reserva CONFIRMED responde 409. Não há estorno depois do débito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.reserve.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * CreateReservationRequest
 */
@JsonPropertyOrder({
    CreateReservationRequest.JSON_PROPERTY_PAYMENT_INTENT_ID,
    CreateReservationRequest.JSON_PROPERTY_PAYER_CPF,
    CreateReservationRequest.JSON_PROPERTY_PAYER_AGENCY,
    CreateReservationRequest.JSON_PROPERTY_PAYER_ACCOUNT,
    CreateReservationRequest.JSON_PROPERTY_AMOUNT,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class CreateReservationRequest {

    public static final String JSON_PROPERTY_PAYMENT_INTENT_ID = "paymentIntentId";
    public static final String JSON_PROPERTY_PAYER_CPF = "payerCpf";
    public static final String JSON_PROPERTY_PAYER_AGENCY = "payerAgency";
    public static final String JSON_PROPERTY_PAYER_ACCOUNT = "payerAccount";
    public static final String JSON_PROPERTY_AMOUNT = "amount";

    /**
     * Id da PaymentIntent. Chave de idempotência da reserva.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
    private UUID paymentIntentId;

    /**
     * CPF do Client dono da conta, só dígitos.
     */
    @NotNull
    @Pattern(regexp = "^[0-9]{11}$")
    @JsonProperty(JSON_PROPERTY_PAYER_CPF)
    private String payerCpf;

    /**
     * Agência da Account.
     */
    @NotNull
    @Size(min = 1, max = 4)
    @JsonProperty(JSON_PROPERTY_PAYER_AGENCY)
    private String payerAgency;

    /**
     * Número da Account.
     */
    @NotNull
    @Size(min = 1, max = 20)
    @JsonProperty(JSON_PROPERTY_PAYER_ACCOUNT)
    private String payerAccount;

    /**
     * Piggies a reservar.
     */
    @NotNull
    @Min(1L)
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    private Long amount;

    public CreateReservationRequest(UUID paymentIntentId, String payerCpf, String payerAgency, String payerAccount, Long amount) {
        this.paymentIntentId = paymentIntentId;
        this.payerCpf = payerCpf;
        this.payerAgency = payerAgency;
        this.payerAccount = payerAccount;
        this.amount = amount;
    }

    /**
     * Id da PaymentIntent. Chave de idempotência da reserva.
     *
     * @return the paymentIntentId property value
     */
    public UUID getPaymentIntentId() {
        return paymentIntentId;
    }

    /**
     * Set the paymentIntentId property value
     *
     * @param paymentIntentId property value to set
     */
    public void setPaymentIntentId(UUID paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
    }

    /**
     * Set paymentIntentId in a chainable fashion.
     *
     * @return The same instance of CreateReservationRequest for chaining.
     */
    public CreateReservationRequest paymentIntentId(UUID paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
        return this;
    }

    /**
     * CPF do Client dono da conta, só dígitos.
     *
     * @return the payerCpf property value
     */
    public String getPayerCpf() {
        return payerCpf;
    }

    /**
     * Set the payerCpf property value
     *
     * @param payerCpf property value to set
     */
    public void setPayerCpf(String payerCpf) {
        this.payerCpf = payerCpf;
    }

    /**
     * Set payerCpf in a chainable fashion.
     *
     * @return The same instance of CreateReservationRequest for chaining.
     */
    public CreateReservationRequest payerCpf(String payerCpf) {
        this.payerCpf = payerCpf;
        return this;
    }

    /**
     * Agência da Account.
     *
     * @return the payerAgency property value
     */
    public String getPayerAgency() {
        return payerAgency;
    }

    /**
     * Set the payerAgency property value
     *
     * @param payerAgency property value to set
     */
    public void setPayerAgency(String payerAgency) {
        this.payerAgency = payerAgency;
    }

    /**
     * Set payerAgency in a chainable fashion.
     *
     * @return The same instance of CreateReservationRequest for chaining.
     */
    public CreateReservationRequest payerAgency(String payerAgency) {
        this.payerAgency = payerAgency;
        return this;
    }

    /**
     * Número da Account.
     *
     * @return the payerAccount property value
     */
    public String getPayerAccount() {
        return payerAccount;
    }

    /**
     * Set the payerAccount property value
     *
     * @param payerAccount property value to set
     */
    public void setPayerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
    }

    /**
     * Set payerAccount in a chainable fashion.
     *
     * @return The same instance of CreateReservationRequest for chaining.
     */
    public CreateReservationRequest payerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
        return this;
    }

    /**
     * Piggies a reservar.
     *
     * @return the amount property value
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Set the amount property value
     *
     * @param amount property value to set
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * Set amount in a chainable fashion.
     *
     * @return The same instance of CreateReservationRequest for chaining.
     */
    public CreateReservationRequest amount(Long amount) {
        this.amount = amount;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var createReservationRequest = (CreateReservationRequest) o;
        return Objects.equals(this.paymentIntentId, createReservationRequest.paymentIntentId)
            && Objects.equals(this.payerCpf, createReservationRequest.payerCpf)
            && Objects.equals(this.payerAgency, createReservationRequest.payerAgency)
            && Objects.equals(this.payerAccount, createReservationRequest.payerAccount)
            && Objects.equals(this.amount, createReservationRequest.amount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(paymentIntentId, payerCpf, payerAgency, payerAccount, amount);
    }

    @Override
    public String toString() {
        return "CreateReservationRequest("
            + "paymentIntentId: " + getPaymentIntentId() + ", "
            + "payerCpf: " + getPayerCpf() + ", "
            + "payerAgency: " + getPayerAgency() + ", "
            + "payerAccount: " + getPayerAccount() + ", "
            + "amount: " + getAmount()
            + ")";
    }

}