/*
 * PiggiesReserveService
 * Reserva o saldo do cliente e confirma o débito. Disponível = balance − reservedBalance.  Entidades persistidas no schema spp_reserve: Client, Account e Reservation. Client e Account não têm endpoint próprio nesta versão; a reserva localiza a conta por CPF, agência e número.  paymentIntentId é único. Repetir a criação, a confirmação ou a liberação com o mesmo pagamento não move saldo de novo.  Liberar uma reserva CONFIRMED responde 409. Não há estorno depois do débito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.reserve.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import co.inter.piggies.reserve.api.model.ReservationStatus;
import java.time.ZonedDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Reservation
 */
@JsonPropertyOrder({
    Reservation.JSON_PROPERTY_ID,
    Reservation.JSON_PROPERTY_PAYMENT_INTENT_ID,
    Reservation.JSON_PROPERTY_ACCOUNT_ID,
    Reservation.JSON_PROPERTY_AMOUNT,
    Reservation.JSON_PROPERTY_STATUS,
    Reservation.JSON_PROPERTY_CREATED_AT,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class Reservation {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_PAYMENT_INTENT_ID = "paymentIntentId";
    public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
    public static final String JSON_PROPERTY_AMOUNT = "amount";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_CREATED_AT = "createdAt";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private UUID id;

    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
    private UUID paymentIntentId;

    /**
     * Account em que reservedBalance e balance foram movimentados.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
    private UUID accountId;

    @NotNull
    @Min(1L)
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    private Long amount;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private ReservationStatus status;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CREATED_AT)
    private ZonedDateTime createdAt;

    public Reservation(UUID id, UUID paymentIntentId, UUID accountId, Long amount, ReservationStatus status, ZonedDateTime createdAt) {
        this.id = id;
        this.paymentIntentId = paymentIntentId;
        this.accountId = accountId;
        this.amount = amount;
        this.status = status;
        this.createdAt = createdAt;
    }

    /**
     * @return the id property value
     */
    public UUID getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of Reservation for chaining.
     */
    public Reservation id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * @return the paymentIntentId property value
     */
    public UUID getPaymentIntentId() {
        return paymentIntentId;
    }

    /**
     * Set the paymentIntentId property value
     *
     * @param paymentIntentId property value to set
     */
    public void setPaymentIntentId(UUID paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
    }

    /**
     * Set paymentIntentId in a chainable fashion.
     *
     * @return The same instance of Reservation for chaining.
     */
    public Reservation paymentIntentId(UUID paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
        return this;
    }

    /**
     * Account em que reservedBalance e balance foram movimentados.
     *
     * @return the accountId property value
     */
    public UUID getAccountId() {
        return accountId;
    }

    /**
     * Set the accountId property value
     *
     * @param accountId property value to set
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Set accountId in a chainable fashion.
     *
     * @return The same instance of Reservation for chaining.
     */
    public Reservation accountId(UUID accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * @return the amount property value
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Set the amount property value
     *
     * @param amount property value to set
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * Set amount in a chainable fashion.
     *
     * @return The same instance of Reservation for chaining.
     */
    public Reservation amount(Long amount) {
        this.amount = amount;
        return this;
    }

    /**
     * @return the status property value
     */
    public ReservationStatus getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(ReservationStatus status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of Reservation for chaining.
     */
    public Reservation status(ReservationStatus status) {
        this.status = status;
        return this;
    }

    /**
     * @return the createdAt property value
     */
    public ZonedDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Set the createdAt property value
     *
     * @param createdAt property value to set
     */
    public void setCreatedAt(ZonedDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Set createdAt in a chainable fashion.
     *
     * @return The same instance of Reservation for chaining.
     */
    public Reservation createdAt(ZonedDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var reservation = (Reservation) o;
        return Objects.equals(this.id, reservation.id)
            && Objects.equals(this.paymentIntentId, reservation.paymentIntentId)
            && Objects.equals(this.accountId, reservation.accountId)
            && Objects.equals(this.amount, reservation.amount)
            && Objects.equals(this.status, reservation.status)
            && Objects.equals(this.createdAt, reservation.createdAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, paymentIntentId, accountId, amount, status, createdAt);
    }

    @Override
    public String toString() {
        return "Reservation("
            + "id: " + getId() + ", "
            + "paymentIntentId: " + getPaymentIntentId() + ", "
            + "accountId: " + getAccountId() + ", "
            + "amount: " + getAmount() + ", "
            + "status: " + getStatus() + ", "
            + "createdAt: " + getCreatedAt()
            + ")";
    }

}