/*
 * PiggiesReserveService
 * Reserva o saldo do cliente e confirma o débito. Disponível = balance − reservedBalance.  Entidades persistidas no schema spp_reserve: Client, Account e Reservation. Client e Account não têm endpoint próprio nesta versão; a reserva localiza a conta por CPF, agência e número.  paymentIntentId é único. Repetir a criação, a confirmação ou a liberação com o mesmo pagamento não move saldo de novo.  Liberar uma reserva CONFIRMED responde 409. Não há estorno depois do débito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.reserve.api;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import co.inter.piggies.reserve.api.model.CreateReservationRequest;
import io.micronaut.http.HttpResponse;
import co.inter.piggies.reserve.api.model.Problem;
import co.inter.piggies.reserve.api.model.Reservation;
import java.util.UUID;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface ReservationsApi {

    /**
     * {@summary Confirma o débito da reserva}
     * Tira o amount de balance e de reservedBalance. A reserva passa a CONFIRMED. Chamar de novo devolve a mesma reserva sem debitar outra vez.
     *
     * @param id Id da Reservation. (required)
     *
     * @return Débito confirmado, ou confirmação já aplicada. (status code 200)
     *         or Reserva não encontrada. (status code 404)
     *         or A reserva já foi liberada e não pode ser debitada. (status code 409)
     */
    @Post("/v1/reservations/{id}/confirm")
    @Produces({"application/json", "application/problem+json"})
    Reservation confirmReservation(
        @PathVariable("id") @NotNull UUID id
    );

    /**
     * {@summary Reserva Piggies na conta do cliente}
     * Aumenta reservedBalance quando o disponível cobre o amount. A reserva nasce em RESERVED.
     *
     * @param createReservationRequest (required)
     *
     * @return Reserva criada. (status code 201)
     *         or Já existia reserva para este paymentIntentId. O saldo não muda. (status code 200)
     *         or Campo inválido, como amount menor que 1. (status code 400)
     *         or Conta do cliente não encontrada. (status code 404)
     *         or Disponível insuficiente para o amount. (status code 422)
     */
    @Post("/v1/reservations")
    @Produces({"application/json", "application/problem+json"})
    HttpResponse<@Valid Reservation> createReservation(
        @Body @NotNull @Valid CreateReservationRequest createReservationRequest
    );

    /**
     * {@summary Libera uma reserva ainda não debitada}
     * Devolve o amount apenas em reservedBalance. balance não muda. A reserva passa a RELEASED. Usada quando a validação do merchant falha.
     *
     * @param id Id da Reservation. (required)
     *
     * @return Reserva liberada, ou liberação já aplicada. (status code 200)
     *         or Reserva não encontrada. (status code 404)
     *         or A reserva já foi confirmada. Não há cancelamento depois do débito. (status code 409)
     */
    @Post("/v1/reservations/{id}/release")
    @Produces({"application/json", "application/problem+json"})
    Reservation releaseReservation(
        @PathVariable("id") @NotNull UUID id
    );

}