/*
 * PiggiesMerchantService
 * Valida o merchant e registra o crédito. Merchant ACTIVE segue no fluxo. INACTIVE ou CNPJ desconhecido interrompem o pagamento.  Entidades persistidas no schema spp_merchant: Merchant e Receivable.  paymentIntentId é único no recebível. Repetir o crédito devolve o mesmo Receivable sem criar outra linha.  Consome spp.payment.confirm e publica spp.payment.confirmed depois do crédito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.merchant.api;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import co.inter.piggies.merchant.api.model.CreateCreditRequest;
import io.micronaut.http.HttpResponse;
import co.inter.piggies.merchant.api.model.Merchant;
import co.inter.piggies.merchant.api.model.Problem;
import co.inter.piggies.merchant.api.model.Receivable;
import co.inter.piggies.merchant.api.model.ValidateMerchantRequest;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface MerchantsApi {

    /**
     * {@summary Registra o recebível e credita o merchant}
     * Grava um Receivable CREDITED para um merchant ACTIVE. O mesmo paymentIntentId devolve o recebível já gravado.
     *
     * @param createCreditRequest (required)
     *
     * @return Recebível criado. (status code 201)
     *         or Já existia recebível para este paymentIntentId. (status code 200)
     *         or Campo inválido, como CNPJ fora do formato ou amount menor que 1. (status code 400)
     *         or CNPJ sem cadastro. (status code 404)
     *         or Merchant inativo. Nenhum recebível é criado. (status code 422)
     */
    @Post("/v1/credits")
    @Produces({"application/json", "application/problem+json"})
    HttpResponse<@Valid Receivable> createCredit(
        @Body @NotNull @Valid CreateCreditRequest createCreditRequest
    );

    /**
     * {@summary Valida se o merchant pode receber Piggies}
     *
     * @param validateMerchantRequest (required)
     *
     * @return Merchant ativo. (status code 200)
     *         or Campo inválido, como CNPJ fora do formato ou amount menor que 1. (status code 400)
     *         or CNPJ sem cadastro. (status code 404)
     *         or Merchant cadastrado com status INACTIVE. (status code 422)
     */
    @Post("/v1/merchants/validate")
    @Produces({"application/json", "application/problem+json"})
    Merchant validateMerchant(
        @Body @NotNull @Valid ValidateMerchantRequest validateMerchantRequest
    );

}