/*
 * PiggiesPaymentCoordinator
 * Borda do app. Registra a intenção de pagamento e devolve 202 antes de reservar saldo, validar o merchant e confirmar.  O header Idempotency-Key é o id da PaymentIntent. Reenviar a mesma chave devolve a intenção já existente, sem abrir outra jornada.  Entidade persistida no schema spp_coordinator: PaymentIntent.  Evento publicado em spp.payment.confirm quando a reserva e a validação concluem. Evento consumido em spp.payment.confirmed para fechar a intenção. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * QR já decodificado mais o pagador conhecido pelo app.
 */
@JsonPropertyOrder({
    CreatePaymentRequest.JSON_PROPERTY_PAYER_CPF,
    CreatePaymentRequest.JSON_PROPERTY_PAYER_AGENCY,
    CreatePaymentRequest.JSON_PROPERTY_PAYER_ACCOUNT,
    CreatePaymentRequest.JSON_PROPERTY_MERCHANT_CNPJ,
    CreatePaymentRequest.JSON_PROPERTY_AMOUNT,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class CreatePaymentRequest {

    public static final String JSON_PROPERTY_PAYER_CPF = "payerCpf";
    public static final String JSON_PROPERTY_PAYER_AGENCY = "payerAgency";
    public static final String JSON_PROPERTY_PAYER_ACCOUNT = "payerAccount";
    public static final String JSON_PROPERTY_MERCHANT_CNPJ = "merchantCnpj";
    public static final String JSON_PROPERTY_AMOUNT = "amount";

    /**
     * CPF do cliente pagador, só dígitos.
     */
    @NotNull
    @Pattern(regexp = "^[0-9]{11}$")
    @JsonProperty(JSON_PROPERTY_PAYER_CPF)
    private String payerCpf;

    @NotNull
    @Size(min = 1, max = 4)
    @JsonProperty(JSON_PROPERTY_PAYER_AGENCY)
    private String payerAgency;

    @NotNull
    @Size(min = 1, max = 20)
    @JsonProperty(JSON_PROPERTY_PAYER_ACCOUNT)
    private String payerAccount;

    /**
     * CNPJ do merchant identificado no QR, só dígitos.
     */
    @NotNull
    @Pattern(regexp = "^[0-9]{14}$")
    @JsonProperty(JSON_PROPERTY_MERCHANT_CNPJ)
    private String merchantCnpj;

    /**
     * Quantidade inteira de Piggies.
     */
    @NotNull
    @Min(1L)
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    private Long amount;

    public CreatePaymentRequest(String payerCpf, String payerAgency, String payerAccount, String merchantCnpj, Long amount) {
        this.payerCpf = payerCpf;
        this.payerAgency = payerAgency;
        this.payerAccount = payerAccount;
        this.merchantCnpj = merchantCnpj;
        this.amount = amount;
    }

    /**
     * CPF do cliente pagador, só dígitos.
     *
     * @return the payerCpf property value
     */
    public String getPayerCpf() {
        return payerCpf;
    }

    /**
     * Set the payerCpf property value
     *
     * @param payerCpf property value to set
     */
    public void setPayerCpf(String payerCpf) {
        this.payerCpf = payerCpf;
    }

    /**
     * Set payerCpf in a chainable fashion.
     *
     * @return The same instance of CreatePaymentRequest for chaining.
     */
    public CreatePaymentRequest payerCpf(String payerCpf) {
        this.payerCpf = payerCpf;
        return this;
    }

    /**
     * @return the payerAgency property value
     */
    public String getPayerAgency() {
        return payerAgency;
    }

    /**
     * Set the payerAgency property value
     *
     * @param payerAgency property value to set
     */
    public void setPayerAgency(String payerAgency) {
        this.payerAgency = payerAgency;
    }

    /**
     * Set payerAgency in a chainable fashion.
     *
     * @return The same instance of CreatePaymentRequest for chaining.
     */
    public CreatePaymentRequest payerAgency(String payerAgency) {
        this.payerAgency = payerAgency;
        return this;
    }

    /**
     * @return the payerAccount property value
     */
    public String getPayerAccount() {
        return payerAccount;
    }

    /**
     * Set the payerAccount property value
     *
     * @param payerAccount property value to set
     */
    public void setPayerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
    }

    /**
     * Set payerAccount in a chainable fashion.
     *
     * @return The same instance of CreatePaymentRequest for chaining.
     */
    public CreatePaymentRequest payerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
        return this;
    }

    /**
     * CNPJ do merchant identificado no QR, só dígitos.
     *
     * @return the merchantCnpj property value
     */
    public String getMerchantCnpj() {
        return merchantCnpj;
    }

    /**
     * Set the merchantCnpj property value
     *
     * @param merchantCnpj property value to set
     */
    public void setMerchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
    }

    /**
     * Set merchantCnpj in a chainable fashion.
     *
     * @return The same instance of CreatePaymentRequest for chaining.
     */
    public CreatePaymentRequest merchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
        return this;
    }

    /**
     * Quantidade inteira de Piggies.
     *
     * @return the amount property value
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Set the amount property value
     *
     * @param amount property value to set
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * Set amount in a chainable fashion.
     *
     * @return The same instance of CreatePaymentRequest for chaining.
     */
    public CreatePaymentRequest amount(Long amount) {
        this.amount = amount;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var createPaymentRequest = (CreatePaymentRequest) o;
        return Objects.equals(this.payerCpf, createPaymentRequest.payerCpf)
            && Objects.equals(this.payerAgency, createPaymentRequest.payerAgency)
            && Objects.equals(this.payerAccount, createPaymentRequest.payerAccount)
            && Objects.equals(this.merchantCnpj, createPaymentRequest.merchantCnpj)
            && Objects.equals(this.amount, createPaymentRequest.amount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(payerCpf, payerAgency, payerAccount, merchantCnpj, amount);
    }

    @Override
    public String toString() {
        return "CreatePaymentRequest("
            + "payerCpf: " + getPayerCpf() + ", "
            + "payerAgency: " + getPayerAgency() + ", "
            + "payerAccount: " + getPayerAccount() + ", "
            + "merchantCnpj: " + getMerchantCnpj() + ", "
            + "amount: " + getAmount()
            + ")";
    }

}