/*
 * PiggiesPaymentCoordinator
 * Borda do app. Registra a intenção de pagamento e devolve 202 antes de reservar saldo, validar o merchant e confirmar.  O header Idempotency-Key é o id da PaymentIntent. Reenviar a mesma chave devolve a intenção já existente, sem abrir outra jornada.  Entidade persistida no schema spp_coordinator: PaymentIntent.  Evento publicado em spp.payment.confirm quando a reserva e a validação concluem. Evento consumido em spp.payment.confirmed para fechar a intenção. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import co.inter.piggies.coordinator.api.model.PaymentStatus;
import java.time.ZonedDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Intenção de pagamento persistida pelo coordinator.
 */
@JsonPropertyOrder({
    PaymentIntent.JSON_PROPERTY_ID,
    PaymentIntent.JSON_PROPERTY_PAYER_CPF,
    PaymentIntent.JSON_PROPERTY_PAYER_AGENCY,
    PaymentIntent.JSON_PROPERTY_PAYER_ACCOUNT,
    PaymentIntent.JSON_PROPERTY_MERCHANT_CNPJ,
    PaymentIntent.JSON_PROPERTY_AMOUNT,
    PaymentIntent.JSON_PROPERTY_STATUS,
    PaymentIntent.JSON_PROPERTY_CREATED_AT,
    PaymentIntent.JSON_PROPERTY_UPDATED_AT,
    PaymentIntent.JSON_PROPERTY_RESERVATION_ID,
    PaymentIntent.JSON_PROPERTY_FAILURE_REASON,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class PaymentIntent {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_PAYER_CPF = "payerCpf";
    public static final String JSON_PROPERTY_PAYER_AGENCY = "payerAgency";
    public static final String JSON_PROPERTY_PAYER_ACCOUNT = "payerAccount";
    public static final String JSON_PROPERTY_MERCHANT_CNPJ = "merchantCnpj";
    public static final String JSON_PROPERTY_AMOUNT = "amount";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
    public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
    public static final String JSON_PROPERTY_RESERVATION_ID = "reservationId";
    public static final String JSON_PROPERTY_FAILURE_REASON = "failureReason";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private UUID id;

    @NotNull
    @Pattern(regexp = "^[0-9]{11}$")
    @JsonProperty(JSON_PROPERTY_PAYER_CPF)
    private String payerCpf;

    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYER_AGENCY)
    private String payerAgency;

    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYER_ACCOUNT)
    private String payerAccount;

    @NotNull
    @Pattern(regexp = "^[0-9]{14}$")
    @JsonProperty(JSON_PROPERTY_MERCHANT_CNPJ)
    private String merchantCnpj;

    @NotNull
    @Min(1L)
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    private Long amount;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private PaymentStatus status;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CREATED_AT)
    private ZonedDateTime createdAt;

    @NotNull
    @JsonProperty(JSON_PROPERTY_UPDATED_AT)
    private ZonedDateTime updatedAt;

    /**
     * Preenchido depois que o PiggiesReserveService cria a reserva.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_RESERVATION_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private UUID reservationId;

    /**
     * Preenchido quando status é FAILED.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_FAILURE_REASON)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String failureReason;

    public PaymentIntent(UUID id, String payerCpf, String payerAgency, String payerAccount, String merchantCnpj, Long amount, PaymentStatus status, ZonedDateTime createdAt, ZonedDateTime updatedAt) {
        this.id = id;
        this.payerCpf = payerCpf;
        this.payerAgency = payerAgency;
        this.payerAccount = payerAccount;
        this.merchantCnpj = merchantCnpj;
        this.amount = amount;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * @return the id property value
     */
    public UUID getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * @return the payerCpf property value
     */
    public String getPayerCpf() {
        return payerCpf;
    }

    /**
     * Set the payerCpf property value
     *
     * @param payerCpf property value to set
     */
    public void setPayerCpf(String payerCpf) {
        this.payerCpf = payerCpf;
    }

    /**
     * Set payerCpf in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent payerCpf(String payerCpf) {
        this.payerCpf = payerCpf;
        return this;
    }

    /**
     * @return the payerAgency property value
     */
    public String getPayerAgency() {
        return payerAgency;
    }

    /**
     * Set the payerAgency property value
     *
     * @param payerAgency property value to set
     */
    public void setPayerAgency(String payerAgency) {
        this.payerAgency = payerAgency;
    }

    /**
     * Set payerAgency in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent payerAgency(String payerAgency) {
        this.payerAgency = payerAgency;
        return this;
    }

    /**
     * @return the payerAccount property value
     */
    public String getPayerAccount() {
        return payerAccount;
    }

    /**
     * Set the payerAccount property value
     *
     * @param payerAccount property value to set
     */
    public void setPayerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
    }

    /**
     * Set payerAccount in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent payerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
        return this;
    }

    /**
     * @return the merchantCnpj property value
     */
    public String getMerchantCnpj() {
        return merchantCnpj;
    }

    /**
     * Set the merchantCnpj property value
     *
     * @param merchantCnpj property value to set
     */
    public void setMerchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
    }

    /**
     * Set merchantCnpj in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent merchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
        return this;
    }

    /**
     * @return the amount property value
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Set the amount property value
     *
     * @param amount property value to set
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * Set amount in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent amount(Long amount) {
        this.amount = amount;
        return this;
    }

    /**
     * @return the status property value
     */
    public PaymentStatus getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(PaymentStatus status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent status(PaymentStatus status) {
        this.status = status;
        return this;
    }

    /**
     * @return the createdAt property value
     */
    public ZonedDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Set the createdAt property value
     *
     * @param createdAt property value to set
     */
    public void setCreatedAt(ZonedDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Set createdAt in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent createdAt(ZonedDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * @return the updatedAt property value
     */
    public ZonedDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Set the updatedAt property value
     *
     * @param updatedAt property value to set
     */
    public void setUpdatedAt(ZonedDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Set updatedAt in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent updatedAt(ZonedDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Preenchido depois que o PiggiesReserveService cria a reserva.
     *
     * @return the reservationId property value
     */
    public UUID getReservationId() {
        return reservationId;
    }

    /**
     * Set the reservationId property value
     *
     * @param reservationId property value to set
     */
    public void setReservationId(UUID reservationId) {
        this.reservationId = reservationId;
    }

    /**
     * Set reservationId in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent reservationId(UUID reservationId) {
        this.reservationId = reservationId;
        return this;
    }

    /**
     * Preenchido quando status é FAILED.
     *
     * @return the failureReason property value
     */
    public String getFailureReason() {
        return failureReason;
    }

    /**
     * Set the failureReason property value
     *
     * @param failureReason property value to set
     */
    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    /**
     * Set failureReason in a chainable fashion.
     *
     * @return The same instance of PaymentIntent for chaining.
     */
    public PaymentIntent failureReason(String failureReason) {
        this.failureReason = failureReason;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var paymentIntent = (PaymentIntent) o;
        return Objects.equals(this.id, paymentIntent.id)
            && Objects.equals(this.payerCpf, paymentIntent.payerCpf)
            && Objects.equals(this.payerAgency, paymentIntent.payerAgency)
            && Objects.equals(this.payerAccount, paymentIntent.payerAccount)
            && Objects.equals(this.merchantCnpj, paymentIntent.merchantCnpj)
            && Objects.equals(this.amount, paymentIntent.amount)
            && Objects.equals(this.status, paymentIntent.status)
            && Objects.equals(this.createdAt, paymentIntent.createdAt)
            && Objects.equals(this.updatedAt, paymentIntent.updatedAt)
            && Objects.equals(this.reservationId, paymentIntent.reservationId)
            && Objects.equals(this.failureReason, paymentIntent.failureReason);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, payerCpf, payerAgency, payerAccount, merchantCnpj, amount, status, createdAt, updatedAt, reservationId, failureReason);
    }

    @Override
    public String toString() {
        return "PaymentIntent("
            + "id: " + getId() + ", "
            + "payerCpf: " + getPayerCpf() + ", "
            + "payerAgency: " + getPayerAgency() + ", "
            + "payerAccount: " + getPayerAccount() + ", "
            + "merchantCnpj: " + getMerchantCnpj() + ", "
            + "amount: " + getAmount() + ", "
            + "status: " + getStatus() + ", "
            + "createdAt: " + getCreatedAt() + ", "
            + "updatedAt: " + getUpdatedAt() + ", "
            + "reservationId: " + getReservationId() + ", "
            + "failureReason: " + getFailureReason()
            + ")";
    }

}