/*
 * PiggiesPaymentCoordinator
 * Borda do app. Registra a intenção de pagamento e devolve 202 antes de reservar saldo, validar o merchant e confirmar.  O header Idempotency-Key é o id da PaymentIntent. Reenviar a mesma chave devolve a intenção já existente, sem abrir outra jornada.  Entidade persistida no schema spp_coordinator: PaymentIntent.  Evento publicado em spp.payment.confirm quando a reserva e a validação concluem. Evento consumido em spp.payment.confirmed para fechar a intenção. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Publicado pelo coordinator no tópico spp.payment.confirm depois que a reserva e a validação do merchant concluem com sucesso.
 */
@JsonPropertyOrder({
    PaymentConfirmEvent.JSON_PROPERTY_PAYMENT_ID,
    PaymentConfirmEvent.JSON_PROPERTY_RESERVATION_ID,
    PaymentConfirmEvent.JSON_PROPERTY_MERCHANT_CNPJ,
    PaymentConfirmEvent.JSON_PROPERTY_AMOUNT,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class PaymentConfirmEvent {

    public static final String JSON_PROPERTY_PAYMENT_ID = "paymentId";
    public static final String JSON_PROPERTY_RESERVATION_ID = "reservationId";
    public static final String JSON_PROPERTY_MERCHANT_CNPJ = "merchantCnpj";
    public static final String JSON_PROPERTY_AMOUNT = "amount";

    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYMENT_ID)
    private UUID paymentId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_RESERVATION_ID)
    private UUID reservationId;

    @NotNull
    @Pattern(regexp = "^[0-9]{14}$")
    @JsonProperty(JSON_PROPERTY_MERCHANT_CNPJ)
    private String merchantCnpj;

    @NotNull
    @Min(1L)
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    private Long amount;

    public PaymentConfirmEvent(UUID paymentId, UUID reservationId, String merchantCnpj, Long amount) {
        this.paymentId = paymentId;
        this.reservationId = reservationId;
        this.merchantCnpj = merchantCnpj;
        this.amount = amount;
    }

    /**
     * @return the paymentId property value
     */
    public UUID getPaymentId() {
        return paymentId;
    }

    /**
     * Set the paymentId property value
     *
     * @param paymentId property value to set
     */
    public void setPaymentId(UUID paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * Set paymentId in a chainable fashion.
     *
     * @return The same instance of PaymentConfirmEvent for chaining.
     */
    public PaymentConfirmEvent paymentId(UUID paymentId) {
        this.paymentId = paymentId;
        return this;
    }

    /**
     * @return the reservationId property value
     */
    public UUID getReservationId() {
        return reservationId;
    }

    /**
     * Set the reservationId property value
     *
     * @param reservationId property value to set
     */
    public void setReservationId(UUID reservationId) {
        this.reservationId = reservationId;
    }

    /**
     * Set reservationId in a chainable fashion.
     *
     * @return The same instance of PaymentConfirmEvent for chaining.
     */
    public PaymentConfirmEvent reservationId(UUID reservationId) {
        this.reservationId = reservationId;
        return this;
    }

    /**
     * @return the merchantCnpj property value
     */
    public String getMerchantCnpj() {
        return merchantCnpj;
    }

    /**
     * Set the merchantCnpj property value
     *
     * @param merchantCnpj property value to set
     */
    public void setMerchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
    }

    /**
     * Set merchantCnpj in a chainable fashion.
     *
     * @return The same instance of PaymentConfirmEvent for chaining.
     */
    public PaymentConfirmEvent merchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
        return this;
    }

    /**
     * @return the amount property value
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Set the amount property value
     *
     * @param amount property value to set
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * Set amount in a chainable fashion.
     *
     * @return The same instance of PaymentConfirmEvent for chaining.
     */
    public PaymentConfirmEvent amount(Long amount) {
        this.amount = amount;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var paymentConfirmEvent = (PaymentConfirmEvent) o;
        return Objects.equals(this.paymentId, paymentConfirmEvent.paymentId)
            && Objects.equals(this.reservationId, paymentConfirmEvent.reservationId)
            && Objects.equals(this.merchantCnpj, paymentConfirmEvent.merchantCnpj)
            && Objects.equals(this.amount, paymentConfirmEvent.amount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(paymentId, reservationId, merchantCnpj, amount);
    }

    @Override
    public String toString() {
        return "PaymentConfirmEvent("
            + "paymentId: " + getPaymentId() + ", "
            + "reservationId: " + getReservationId() + ", "
            + "merchantCnpj: " + getMerchantCnpj() + ", "
            + "amount: " + getAmount()
            + ")";
    }

}