/*
 * PiggiesPaymentCoordinator
 * Borda do app. Registra a intenção de pagamento e devolve 202 antes de reservar saldo, validar o merchant e confirmar.  O header Idempotency-Key é o id da PaymentIntent. Reenviar a mesma chave devolve a intenção já existente, sem abrir outra jornada.  Entidade persistida no schema spp_coordinator: PaymentIntent.  Evento publicado em spp.payment.confirm quando a reserva e a validação concluem. Evento consumido em spp.payment.confirmed para fechar a intenção. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.time.ZonedDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Consumido pelo coordinator no tópico spp.payment.confirmed. Ao receber, a intenção passa a CONFIRMED.
 */
@JsonPropertyOrder({
    PaymentConfirmedEvent.JSON_PROPERTY_PAYMENT_ID,
    PaymentConfirmedEvent.JSON_PROPERTY_MERCHANT_CNPJ,
    PaymentConfirmedEvent.JSON_PROPERTY_AMOUNT,
    PaymentConfirmedEvent.JSON_PROPERTY_CREDITED_AT,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class PaymentConfirmedEvent {

    public static final String JSON_PROPERTY_PAYMENT_ID = "paymentId";
    public static final String JSON_PROPERTY_MERCHANT_CNPJ = "merchantCnpj";
    public static final String JSON_PROPERTY_AMOUNT = "amount";
    public static final String JSON_PROPERTY_CREDITED_AT = "creditedAt";

    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYMENT_ID)
    private UUID paymentId;

    @NotNull
    @Pattern(regexp = "^[0-9]{14}$")
    @JsonProperty(JSON_PROPERTY_MERCHANT_CNPJ)
    private String merchantCnpj;

    @NotNull
    @Min(1L)
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    private Long amount;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CREDITED_AT)
    private ZonedDateTime creditedAt;

    public PaymentConfirmedEvent(UUID paymentId, String merchantCnpj, Long amount, ZonedDateTime creditedAt) {
        this.paymentId = paymentId;
        this.merchantCnpj = merchantCnpj;
        this.amount = amount;
        this.creditedAt = creditedAt;
    }

    /**
     * @return the paymentId property value
     */
    public UUID getPaymentId() {
        return paymentId;
    }

    /**
     * Set the paymentId property value
     *
     * @param paymentId property value to set
     */
    public void setPaymentId(UUID paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * Set paymentId in a chainable fashion.
     *
     * @return The same instance of PaymentConfirmedEvent for chaining.
     */
    public PaymentConfirmedEvent paymentId(UUID paymentId) {
        this.paymentId = paymentId;
        return this;
    }

    /**
     * @return the merchantCnpj property value
     */
    public String getMerchantCnpj() {
        return merchantCnpj;
    }

    /**
     * Set the merchantCnpj property value
     *
     * @param merchantCnpj property value to set
     */
    public void setMerchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
    }

    /**
     * Set merchantCnpj in a chainable fashion.
     *
     * @return The same instance of PaymentConfirmedEvent for chaining.
     */
    public PaymentConfirmedEvent merchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
        return this;
    }

    /**
     * @return the amount property value
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Set the amount property value
     *
     * @param amount property value to set
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * Set amount in a chainable fashion.
     *
     * @return The same instance of PaymentConfirmedEvent for chaining.
     */
    public PaymentConfirmedEvent amount(Long amount) {
        this.amount = amount;
        return this;
    }

    /**
     * @return the creditedAt property value
     */
    public ZonedDateTime getCreditedAt() {
        return creditedAt;
    }

    /**
     * Set the creditedAt property value
     *
     * @param creditedAt property value to set
     */
    public void setCreditedAt(ZonedDateTime creditedAt) {
        this.creditedAt = creditedAt;
    }

    /**
     * Set creditedAt in a chainable fashion.
     *
     * @return The same instance of PaymentConfirmedEvent for chaining.
     */
    public PaymentConfirmedEvent creditedAt(ZonedDateTime creditedAt) {
        this.creditedAt = creditedAt;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var paymentConfirmedEvent = (PaymentConfirmedEvent) o;
        return Objects.equals(this.paymentId, paymentConfirmedEvent.paymentId)
            && Objects.equals(this.merchantCnpj, paymentConfirmedEvent.merchantCnpj)
            && Objects.equals(this.amount, paymentConfirmedEvent.amount)
            && Objects.equals(this.creditedAt, paymentConfirmedEvent.creditedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(paymentId, merchantCnpj, amount, creditedAt);
    }

    @Override
    public String toString() {
        return "PaymentConfirmedEvent("
            + "paymentId: " + getPaymentId() + ", "
            + "merchantCnpj: " + getMerchantCnpj() + ", "
            + "amount: " + getAmount() + ", "
            + "creditedAt: " + getCreditedAt()
            + ")";
    }

}