/*
 * PiggiesPaymentCoordinator
 * Borda do app. Registra a intenção de pagamento e devolve 202 antes de reservar saldo, validar o merchant e confirmar.  O header Idempotency-Key é o id da PaymentIntent. Reenviar a mesma chave devolve a intenção já existente, sem abrir outra jornada.  Entidade persistida no schema spp_coordinator: PaymentIntent.  Evento publicado em spp.payment.confirm quando a reserva e a validação concluem. Evento consumido em spp.payment.confirmed para fechar a intenção. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import co.inter.piggies.coordinator.api.model.PaymentStatus;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Resposta imediata da borda. paymentId é o Idempotency-Key.
 */
@JsonPropertyOrder({
    PaymentAccepted.JSON_PROPERTY_PAYMENT_ID,
    PaymentAccepted.JSON_PROPERTY_STATUS,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class PaymentAccepted {

    public static final String JSON_PROPERTY_PAYMENT_ID = "paymentId";
    public static final String JSON_PROPERTY_STATUS = "status";

    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYMENT_ID)
    private UUID paymentId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private PaymentStatus status;

    public PaymentAccepted(UUID paymentId, PaymentStatus status) {
        this.paymentId = paymentId;
        this.status = status;
    }

    /**
     * @return the paymentId property value
     */
    public UUID getPaymentId() {
        return paymentId;
    }

    /**
     * Set the paymentId property value
     *
     * @param paymentId property value to set
     */
    public void setPaymentId(UUID paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * Set paymentId in a chainable fashion.
     *
     * @return The same instance of PaymentAccepted for chaining.
     */
    public PaymentAccepted paymentId(UUID paymentId) {
        this.paymentId = paymentId;
        return this;
    }

    /**
     * @return the status property value
     */
    public PaymentStatus getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(PaymentStatus status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of PaymentAccepted for chaining.
     */
    public PaymentAccepted status(PaymentStatus status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var paymentAccepted = (PaymentAccepted) o;
        return Objects.equals(this.paymentId, paymentAccepted.paymentId)
            && Objects.equals(this.status, paymentAccepted.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(paymentId, status);
    }

    @Override
    public String toString() {
        return "PaymentAccepted("
            + "paymentId: " + getPaymentId() + ", "
            + "status: " + getStatus()
            + ")";
    }

}