/*
 * PiggiesPaymentCoordinator
 * Borda do app. Registra a intenção de pagamento e devolve 202 antes de reservar saldo, validar o merchant e confirmar.  O header Idempotency-Key é o id da PaymentIntent. Reenviar a mesma chave devolve a intenção já existente, sem abrir outra jornada.  Entidade persistida no schema spp_coordinator: PaymentIntent.  Evento publicado em spp.payment.confirm quando a reserva e a validação concluem. Evento consumido em spp.payment.confirmed para fechar a intenção. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.net.URI;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * RFC 9457 application/problem+json
 */
@JsonPropertyOrder({
    Problem.JSON_PROPERTY_TITLE,
    Problem.JSON_PROPERTY_STATUS,
    Problem.JSON_PROPERTY_TYPE,
    Problem.JSON_PROPERTY_DETAIL,
    Problem.JSON_PROPERTY_INSTANCE,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class Problem {

    public static final String JSON_PROPERTY_TITLE = "title";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_TYPE = "type";
    public static final String JSON_PROPERTY_DETAIL = "detail";
    public static final String JSON_PROPERTY_INSTANCE = "instance";

    @NotNull
    @JsonProperty(JSON_PROPERTY_TITLE)
    private String title;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private Integer status;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private URI type;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_DETAIL)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String detail;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_INSTANCE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private URI instance;

    public Problem(String title, Integer status) {
        this.title = title;
        this.status = status;
    }

    /**
     * @return the title property value
     */
    public String getTitle() {
        return title;
    }

    /**
     * Set the title property value
     *
     * @param title property value to set
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Set title in a chainable fashion.
     *
     * @return The same instance of Problem for chaining.
     */
    public Problem title(String title) {
        this.title = title;
        return this;
    }

    /**
     * @return the status property value
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of Problem for chaining.
     */
    public Problem status(Integer status) {
        this.status = status;
        return this;
    }

    /**
     * @return the type property value
     */
    public URI getType() {
        return type;
    }

    /**
     * Set the type property value
     *
     * @param type property value to set
     */
    public void setType(URI type) {
        this.type = type;
    }

    /**
     * Set type in a chainable fashion.
     *
     * @return The same instance of Problem for chaining.
     */
    public Problem type(URI type) {
        this.type = type;
        return this;
    }

    /**
     * @return the detail property value
     */
    public String getDetail() {
        return detail;
    }

    /**
     * Set the detail property value
     *
     * @param detail property value to set
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * Set detail in a chainable fashion.
     *
     * @return The same instance of Problem for chaining.
     */
    public Problem detail(String detail) {
        this.detail = detail;
        return this;
    }

    /**
     * @return the instance property value
     */
    public URI getInstance() {
        return instance;
    }

    /**
     * Set the instance property value
     *
     * @param instance property value to set
     */
    public void setInstance(URI instance) {
        this.instance = instance;
    }

    /**
     * Set instance in a chainable fashion.
     *
     * @return The same instance of Problem for chaining.
     */
    public Problem instance(URI instance) {
        this.instance = instance;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var problem = (Problem) o;
        return Objects.equals(this.title, problem.title)
            && Objects.equals(this.status, problem.status)
            && Objects.equals(this.type, problem.type)
            && Objects.equals(this.detail, problem.detail)
            && Objects.equals(this.instance, problem.instance);
    }

    @Override
    public int hashCode() {
        return Objects.hash(title, status, type, detail, instance);
    }

    @Override
    public String toString() {
        return "Problem("
            + "title: " + getTitle() + ", "
            + "status: " + getStatus() + ", "
            + "type: " + getType() + ", "
            + "detail: " + getDetail() + ", "
            + "instance: " + getInstance()
            + ")";
    }

}