/*
 * PiggiesReserveService
 * Reserva o saldo do cliente e confirma o débito. Disponível = balance − reservedBalance.  Entidades persistidas no schema spp_reserve: Client, Account e Reservation. Client e Account não têm endpoint próprio nesta versão; a reserva localiza a conta por CPF, agência e número.  paymentIntentId é único. Repetir a criação, a confirmação ou a liberação com o mesmo pagamento não move saldo de novo.  Liberar uma reserva CONFIRMED responde 409. Não há estorno depois do débito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.client.reserve.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Titular persistido pelo reserve. Sem endpoint nesta versão.
 */
@JsonPropertyOrder({
    ModelClient.JSON_PROPERTY_ID,
    ModelClient.JSON_PROPERTY_NAME,
    ModelClient.JSON_PROPERTY_CPF,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautClientCodegen")
public class ModelClient {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_NAME = "name";
    public static final String JSON_PROPERTY_CPF = "cpf";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private UUID id;

    @NotNull
    @JsonProperty(JSON_PROPERTY_NAME)
    private String name;

    /**
     * Único.
     */
    @NotNull
    @Pattern(regexp = "^[0-9]{11}$")
    @JsonProperty(JSON_PROPERTY_CPF)
    private String cpf;

    public ModelClient(UUID id, String name, String cpf) {
        this.id = id;
        this.name = name;
        this.cpf = cpf;
    }

    /**
     * @return the id property value
     */
    public UUID getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of ModelClient for chaining.
     */
    public ModelClient id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * @return the name property value
     */
    public String getName() {
        return name;
    }

    /**
     * Set the name property value
     *
     * @param name property value to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Set name in a chainable fashion.
     *
     * @return The same instance of ModelClient for chaining.
     */
    public ModelClient name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Único.
     *
     * @return the cpf property value
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * Set the cpf property value
     *
     * @param cpf property value to set
     */
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    /**
     * Set cpf in a chainable fashion.
     *
     * @return The same instance of ModelClient for chaining.
     */
    public ModelClient cpf(String cpf) {
        this.cpf = cpf;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var client = (ModelClient) o;
        return Objects.equals(this.id, client.id)
            && Objects.equals(this.name, client.name)
            && Objects.equals(this.cpf, client.cpf);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, cpf);
    }

    @Override
    public String toString() {
        return "ModelClient("
            + "id: " + getId() + ", "
            + "name: " + getName() + ", "
            + "cpf: " + getCpf()
            + ")";
    }

}