/*
 * PiggiesPaymentCoordinator
 * Borda do app. Registra a intenção de pagamento e devolve 202 antes de reservar saldo, validar o merchant e confirmar.  O header Idempotency-Key é o id da PaymentIntent. Reenviar a mesma chave devolve a intenção já existente, sem abrir outra jornada.  Entidade persistida no schema spp_coordinator: PaymentIntent.  Evento publicado em spp.payment.confirm quando a reserva e a validação concluem. Evento consumido em spp.payment.confirmed para fechar a intenção. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.api;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import co.inter.piggies.coordinator.api.model.CreatePaymentRequest;
import io.micronaut.http.HttpResponse;
import co.inter.piggies.coordinator.api.model.PaymentAccepted;
import co.inter.piggies.coordinator.api.model.PaymentIntent;
import co.inter.piggies.coordinator.api.model.Problem;
import java.util.UUID;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface PaymentsApi {

    /**
     * {@summary Inicia um pagamento}
     * Persiste a intenção em PROCESSING e responde 202. Reserva, validação e confirmação acontecem depois desta resposta.
     *
     * @param idempotencyKey UUID da intenção. Repetir a chave devolve o pagamento já criado. (required)
     * @param createPaymentRequest (required)
     *
     * @return Intenção registrada. O status pode já estar adiantado quando a chave é reenviada. (status code 202)
     *         or Campo inválido, como amount menor que 1 ou documento fora do formato. (status code 400)
     */
    @Post("/v1/payments")
    @Produces({"application/json", "application/problem+json"})
    HttpResponse<@Valid PaymentAccepted> createPayment(
        @Header("Idempotency-Key") @NotNull UUID idempotencyKey,
        @Body @NotNull @Valid CreatePaymentRequest createPaymentRequest
    );

    /**
     * {@summary Consulta a intenção de pagamento}
     *
     * @param id Id da PaymentIntent, igual ao Idempotency-Key enviado na criação. (required)
     *
     * @return Estado atual da intenção (status code 200)
     *         or Campo inválido, como amount menor que 1 ou documento fora do formato. (status code 400)
     *         or Intenção não encontrada. (status code 404)
     */
    @Get("/v1/payments/{id}")
    @Produces({"application/json", "application/problem+json"})
    PaymentIntent getPayment(
        @PathVariable("id") @NotNull UUID id
    );

}