/*
 * PiggiesMerchantService
 * Valida o merchant e registra o crédito. Merchant ACTIVE segue no fluxo. INACTIVE ou CNPJ desconhecido interrompem o pagamento.  Entidades persistidas no schema spp_merchant: Merchant e Receivable.  paymentIntentId é único no recebível. Repetir o crédito devolve o mesmo Receivable sem criar outra linha.  Consome spp.payment.confirm e publica spp.payment.confirmed depois do crédito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.client.merchant.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * CreateCreditRequest
 */
@JsonPropertyOrder({
    CreateCreditRequest.JSON_PROPERTY_PAYMENT_INTENT_ID,
    CreateCreditRequest.JSON_PROPERTY_MERCHANT_CNPJ,
    CreateCreditRequest.JSON_PROPERTY_AMOUNT,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautClientCodegen")
public class CreateCreditRequest {

    public static final String JSON_PROPERTY_PAYMENT_INTENT_ID = "paymentIntentId";
    public static final String JSON_PROPERTY_MERCHANT_CNPJ = "merchantCnpj";
    public static final String JSON_PROPERTY_AMOUNT = "amount";

    /**
     * Id da PaymentIntent. Chave de idempotência do recebível.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
    private UUID paymentIntentId;

    @NotNull
    @Pattern(regexp = "^[0-9]{14}$")
    @JsonProperty(JSON_PROPERTY_MERCHANT_CNPJ)
    private String merchantCnpj;

    /**
     * Piggies a creditar.
     */
    @NotNull
    @Min(1L)
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    private Long amount;

    public CreateCreditRequest(UUID paymentIntentId, String merchantCnpj, Long amount) {
        this.paymentIntentId = paymentIntentId;
        this.merchantCnpj = merchantCnpj;
        this.amount = amount;
    }

    /**
     * Id da PaymentIntent. Chave de idempotência do recebível.
     *
     * @return the paymentIntentId property value
     */
    public UUID getPaymentIntentId() {
        return paymentIntentId;
    }

    /**
     * Set the paymentIntentId property value
     *
     * @param paymentIntentId property value to set
     */
    public void setPaymentIntentId(UUID paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
    }

    /**
     * Set paymentIntentId in a chainable fashion.
     *
     * @return The same instance of CreateCreditRequest for chaining.
     */
    public CreateCreditRequest paymentIntentId(UUID paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
        return this;
    }

    /**
     * @return the merchantCnpj property value
     */
    public String getMerchantCnpj() {
        return merchantCnpj;
    }

    /**
     * Set the merchantCnpj property value
     *
     * @param merchantCnpj property value to set
     */
    public void setMerchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
    }

    /**
     * Set merchantCnpj in a chainable fashion.
     *
     * @return The same instance of CreateCreditRequest for chaining.
     */
    public CreateCreditRequest merchantCnpj(String merchantCnpj) {
        this.merchantCnpj = merchantCnpj;
        return this;
    }

    /**
     * Piggies a creditar.
     *
     * @return the amount property value
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Set the amount property value
     *
     * @param amount property value to set
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * Set amount in a chainable fashion.
     *
     * @return The same instance of CreateCreditRequest for chaining.
     */
    public CreateCreditRequest amount(Long amount) {
        this.amount = amount;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var createCreditRequest = (CreateCreditRequest) o;
        return Objects.equals(this.paymentIntentId, createCreditRequest.paymentIntentId)
            && Objects.equals(this.merchantCnpj, createCreditRequest.merchantCnpj)
            && Objects.equals(this.amount, createCreditRequest.amount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(paymentIntentId, merchantCnpj, amount);
    }

    @Override
    public String toString() {
        return "CreateCreditRequest("
            + "paymentIntentId: " + getPaymentIntentId() + ", "
            + "merchantCnpj: " + getMerchantCnpj() + ", "
            + "amount: " + getAmount()
            + ")";
    }

}