/*
 * PiggiesMerchantService
 * Valida o merchant e registra o crédito. Merchant ACTIVE segue no fluxo. INACTIVE ou CNPJ desconhecido interrompem o pagamento.  Entidades persistidas no schema spp_merchant: Merchant e Receivable.  paymentIntentId é único no recebível. Repetir o crédito devolve o mesmo Receivable sem criar outra linha.  Consome spp.payment.confirm e publica spp.payment.confirmed depois do crédito. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package co.inter.piggies.coordinator.client.merchant.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import co.inter.piggies.coordinator.client.merchant.model.MerchantStatus;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Merchant
 */
@JsonPropertyOrder({
    Merchant.JSON_PROPERTY_ID,
    Merchant.JSON_PROPERTY_NAME,
    Merchant.JSON_PROPERTY_CNPJ,
    Merchant.JSON_PROPERTY_AGENCY,
    Merchant.JSON_PROPERTY_ACCOUNT_NUMBER,
    Merchant.JSON_PROPERTY_STATUS,
})
@Serdeable
@Generated("io.micronaut.openapi.generator.JavaMicronautClientCodegen")
public class Merchant {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_NAME = "name";
    public static final String JSON_PROPERTY_CNPJ = "cnpj";
    public static final String JSON_PROPERTY_AGENCY = "agency";
    public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "accountNumber";
    public static final String JSON_PROPERTY_STATUS = "status";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private UUID id;

    @NotNull
    @JsonProperty(JSON_PROPERTY_NAME)
    private String name;

    /**
     * Único.
     */
    @NotNull
    @Pattern(regexp = "^[0-9]{14}$")
    @JsonProperty(JSON_PROPERTY_CNPJ)
    private String cnpj;

    @NotNull
    @JsonProperty(JSON_PROPERTY_AGENCY)
    private String agency;

    /**
     * Conta em que o crédito é registrado.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
    private String accountNumber;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private MerchantStatus status;

    public Merchant(UUID id, String name, String cnpj, String agency, String accountNumber, MerchantStatus status) {
        this.id = id;
        this.name = name;
        this.cnpj = cnpj;
        this.agency = agency;
        this.accountNumber = accountNumber;
        this.status = status;
    }

    /**
     * @return the id property value
     */
    public UUID getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of Merchant for chaining.
     */
    public Merchant id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * @return the name property value
     */
    public String getName() {
        return name;
    }

    /**
     * Set the name property value
     *
     * @param name property value to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Set name in a chainable fashion.
     *
     * @return The same instance of Merchant for chaining.
     */
    public Merchant name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Único.
     *
     * @return the cnpj property value
     */
    public String getCnpj() {
        return cnpj;
    }

    /**
     * Set the cnpj property value
     *
     * @param cnpj property value to set
     */
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    /**
     * Set cnpj in a chainable fashion.
     *
     * @return The same instance of Merchant for chaining.
     */
    public Merchant cnpj(String cnpj) {
        this.cnpj = cnpj;
        return this;
    }

    /**
     * @return the agency property value
     */
    public String getAgency() {
        return agency;
    }

    /**
     * Set the agency property value
     *
     * @param agency property value to set
     */
    public void setAgency(String agency) {
        this.agency = agency;
    }

    /**
     * Set agency in a chainable fashion.
     *
     * @return The same instance of Merchant for chaining.
     */
    public Merchant agency(String agency) {
        this.agency = agency;
        return this;
    }

    /**
     * Conta em que o crédito é registrado.
     *
     * @return the accountNumber property value
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Set the accountNumber property value
     *
     * @param accountNumber property value to set
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Set accountNumber in a chainable fashion.
     *
     * @return The same instance of Merchant for chaining.
     */
    public Merchant accountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }

    /**
     * @return the status property value
     */
    public MerchantStatus getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(MerchantStatus status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of Merchant for chaining.
     */
    public Merchant status(MerchantStatus status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var merchant = (Merchant) o;
        return Objects.equals(this.id, merchant.id)
            && Objects.equals(this.name, merchant.name)
            && Objects.equals(this.cnpj, merchant.cnpj)
            && Objects.equals(this.agency, merchant.agency)
            && Objects.equals(this.accountNumber, merchant.accountNumber)
            && Objects.equals(this.status, merchant.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, cnpj, agency, accountNumber, status);
    }

    @Override
    public String toString() {
        return "Merchant("
            + "id: " + getId() + ", "
            + "name: " + getName() + ", "
            + "cnpj: " + getCnpj() + ", "
            + "agency: " + getAgency() + ", "
            + "accountNumber: " + getAccountNumber() + ", "
            + "status: " + getStatus()
            + ")";
    }

}